### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by stanwarri** [SimpleSoftwareIO/simple-sms#1]
I want to confirm if this works for Laravel 5

**Comment by SimplyCorey** [comment]
@stanwarri  I added basic support for Laravel 5 today and released it as a beta.  I have not had a lot of time to test the changes.  Please check it out and report back :wink:

**Comment by stanwarri** [comment]
@SimplyCorey Well done. I will test and give you feedback.

**Comment by stanwarri** [comment]
Your boot function should be 

```
  public function boot()
{
    $this->publishes([
        __DIR__.'/../../config/config.php' => config_path('sms.php'),
    ]);
}
```

Thanks

**Comment by SimplyCorey** [comment]
@stanwarri I would be interested in why you believe that is correct?  Currently the publish command generates a new `sms.php` file under the `config` folder which I believe is better because it keeps everything separate from the Laravel config files.  I also tried your boot method and it generates an error of `Can't locate path.`  Did you have issues with the vendor:publish command with the following?

```
public function boot()
{
    $this->publishes([
        __DIR__.'/../../config/sms.php' => config_path('sms.php'),
    ]);
}
```

How was the documentation?  Was it easy to follow?

Again, thank you!

**Comment by stanwarri** [comment]
Hello @SimplyCorey There was an error with vendor:publish. The config file in the src folder is 'config.php' and not 'sms.php'

**Comment by SimplyCorey** [comment]
@stanwarri I see what is happening now.  On my development machine, the config file is called `sms.php`  For some reason, this did not sync when I did my last git push.

**Comment by neeravp** [comment]
I tried with laravel 5 using twilio driver but it gives an error as under:

```
Services_Twilio_TinyHttpException in TinyHttp.php line 111:   
SSL certificate problem: self signed certificate in certificate chain  
```

What could be the issue?

**Comment by SimplyCorey** [comment]
@neeravp  Can you please provide an error log for this?

**Comment by neeravp** [comment]
Sorry for responding late but the thing is that I am traveling so not able to reproduce the error  and its log. Will do it in a couple of days when I am back.

**Comment by SimplyCorey** [comment]
@neeravp Any luck with this?  I am unable to reproduce this error and I am looking at releasing this as stable tomorrow.  Thank you

**Comment by SimplyCorey** [comment]
@neeravp I can not reproduce this error.  I would ensure your openssl is working with your server.

**Comment by SimplyCorey** [comment]
Simple-SMS 2.0.0 is released.
