### ISSUE TITLE
Eztexting - GuzzleHttp\Exception\ClientException] Client error: 403

### ISSUE THREAD

**Issue by mfakhrys** [SimpleSoftwareIO/simple-sms#11]
I got this error when using eztexting driver.
Fyi, I use the correct username and password.
 Can you help me?

**Comment by mfakhrys** [comment]
Nvm, somehow it doesn't appear again.

**Comment by dhildreth** [comment]
I realize this is old and closed, but I'm experiencing the same thing.

    [GuzzleHttp\Exception\ClientException]                                                                               
      Client error: `POST https://app.eztexting.com/sending/messages?format=json` resulted in a 
    `403 Forbidden` response:  
      {"Response":{"Status":"Failure","Code":403,"Errors":["Access Forbidden"]}}

I'm hoping it starts to 'just work' like it did for fsyaugy, but I'm not wanting to hold my breath.  Any suggestions would be appreciated.  If I need to, I'll open a new ticket, just let me know.

**Comment by SimplyCorey** [comment]
Have you double checked your config options and ensured that you are passing in the correct api keys?

**Comment by dhildreth** [comment]
I have ensured I'm using the correct username and password.  From my understanding, there wasn't any other API keys to punch in unless you were planning on receiving text messages as well.

https://www.simplesoftware.io/docs/simple-sms#docs-ez-texting-driver

(By the way, the short number may have been updated to 797979 from 313131 which is documented)

**Comment by SimplyCorey** [comment]
Correct, you shoul djust need your username and password for eztexting.  Ill have to take a look at it and see what is going on.  a 403 error sounds like something is wrong on eztexting side though.

**Comment by dhildreth** [comment]
I'd agree with that statement, but I would sure appreciate any help I can get.  Maybe their API has changed somewhat?

**Comment by SimplyCorey** [comment]
I'll have to look at the code, its been awhile.  A quick look at their docs suggests it hasnt changed yet.  If you want to dd($response) here: https://github.com/SimpleSoftwareIO/simple-sms/blob/develop/src/MakesRequests.php#L136 it may give some insight of what's happening.

https://www.eztexting.com/developers/sms-api-documentation/rest#Sending


I plan on coming around and catching up with SMS, but I have been swamped with other work.

**Comment by dhildreth** [comment]
Thanks for the tip.

I added dd($this->getAuth) above the client->post() line and it prints out null.  I found that to be surprising.

**Comment by SimplyCorey** [comment]
That's expected.  For some reason extexting accepts the username/password in the body and not the header.  If you dd the body, you should see it.

**Comment by dhildreth** [comment]
Oh, yup! There it is.  The output of the dd($response) by the way is the same as the error I posted above.

     [GuzzleHttp\Exception\ClientException]                                                                               
      Client error: `POST https://app.eztexting.com/sending/messages?format=json` resulted in a `403 Forbidden` response:  
      {"Response":{"Status":"Failure","Code":403,"Errors":["Access Forbidden"]}}

**Comment by dhildreth** [comment]
Oh, you know what... I just thought of this.  I'm using their free plan.  I wonder if they're restricting API access.  Let me get in touch with them and see what they say.

Thanks.

**Comment by SimplyCorey** [comment]
Please do and get back to me on that.  We should add it to the docs if that is the case.

**Comment by dhildreth** [comment]
Yup. That's the case.  They do not allow API access when you have a free account.  You must have a paid account.

**Comment by dhildreth** [comment]
I'll keep looking around for a free SMS provider with access to the API.  I'll start with the ones you have on your list and then go from there.  Or, I'll just default back to the email gateways.  Thanks for your help.

**Comment by SimplyCorey** [comment]
Thanks for checking that out and it is good to know.

**Comment by dhildreth** [comment]
Also just found out that you can use "anytime credits".  I have 100.  I'll ride it out until I'm out. :-)
