### ISSUE TITLE
Driver [Selected Driver] not supported.

### ISSUE THREAD

**Issue by kieranbarlow** [SimpleSoftwareIO/simple-sms#18]
I've just pulled in this awesome service but I can't get it too work..
I keep getting the message: Driver [Selected Driver] not supported.
I've changed / choosen the twilio driver but can't get any further.
I edited both the config/sms.php file and the vendor/simplesoftwareIO/simple-sms/src/config/sms,php

My file: 

```
return [
    'driver' => 'twilio',
    'from' => '+44mytwilionumber',
    'callfire' => [
        'app_login' => 'Your CallFire API Login',
        'app_password' => 'Your CallFire API Password'
    ],
    'eztexting' => [
        'username' => 'Your EZTexting Username',
        'password' => 'Your EZTexting Password'
    ],
    'labsmobile' => [
        'client' => 'Your client ID',
        'username' => 'Your Usernbame',
        'password' => 'Your Password',
        'test' => false
    ],
    'mozeo' => [
        'company_key' => 'Your Mozeo Company Key',
        'username' => 'Your Mozeo Username',
        'password' => 'Your Mozeo Password'
    ],
    'nexmo' => [
        'api_key' => 'Your Nexmo api key',
        'api_secret' => 'Your Nexmo api secret'
    ],
    'twilio' => [
        'account_sid' => 'twilio SID',
        'auth_token' => 'twilio Key',
        'verify' => true,
    ]
];
```

Any help would be greatly appreciated - I followed the step by step instructions:

"php": ">=5.5.9",
"guzzlehttp/guzzle": "~5.3|~6.0",
 "simplesoftwareio/simple-sms": "~2"

**Comment by SimplyCorey** [comment]
Hey there,

I just tested the latest package and everything worked on our end.  You should be editing the `config/sms.php` file.  

I would suggest deleting your `config/sms.php` file and then running this artisan command: `php artisan vendor:publish.`  Afterwards, edit your `config/sms.php` file.

If should look something like this afterwards

```
return [
    'driver' => 'twilio',
    'from' => '+15555555555',
    'twilio' => [
        'account_sid' => 'Your SID',
        'auth_token' => 'Your Token',
        'verify' => true,
    ]
];
```

Let me know if this solves your problem or if you need anymore help!

**Comment by kieranbarlow** [comment]
Hey

Fixed the issue seemed it was the application cache! Thanks for the reply though.

Kieran

Sent from my iPhone

On 31 Jan 2016, at 01:06, Corey McCormick <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey there,

I just tested the latest package and everything worked on our end. You should be editing the config/sms.php file.

I would suggest deleting your config/sms.php file and then running this artisan command: php artisan vendor:publish. Afterwards, edit your config/sms.php file.

If should look something like this afterwards

return [
    'driver' => 'twilio',
    'from' => '+15555555555',
    'twilio' => [
        'account_sid' => 'Your SID',
        'auth_token' => 'Your Token',
        'verify' => true,
    ]
];

Let me know if this solves your problem or if you need anymore help!

##

**Comment by SimplyCorey** [comment]
Ah that has gotten me a few times.  Glad you figured it out!
