### ISSUE TITLE
[improvement] Remove message text from views

### ISSUE THREAD

**Issue by iberflow** [SimpleSoftwareIO/simple-sms#2]
It seems like it's an overhead to store the message text in blade files. I would assume that a lot of folks would pull the text from a database, translation file, etc. Why was this approached selected?

**Comment by SimplyCorey** [comment]
This approach was used to allow users to have templates in their blade files and then fill in the templates with things such as usernames ext.  

I can add a "simple" method which can be used to send a message without a blade template file.

**Comment by SimplyCorey** [comment]
@ignasbernotas  You can now send simple messages with the latest dev branch.

```
SMS::send('This is my message', [], function($sms) {
  $sms->to('+15555555555');
});
```
