### ISSUE TITLE
Incorrect class is called in code

### ISSUE THREAD

**Issue by adetoola** [SimpleSoftwareIO/simple-sms#20]
Class mailer is being referenced instead of sms in [https://github.com/SimpleSoftwareIO/simple-sms/blob/master/src/SimpleSoftwareIO/SMS/SMS.php](url) on line 257

`$this->queue->later($delay, 'mailer@handleQueuedMessage', compact('view', 'data', 'callback'), $queue);`

**Comment by SimplyCorey** [comment]
Hey there!

Thanks for reporting this.  I'll get a bug fixed for this pushed shortly.
