### ISSUE TITLE
Where to set up config file 

### ISSUE THREAD

**Issue by parithiban** [SimpleSoftwareIO/simple-sms#21]
Hi,

I am new to laravel. I have installed your package i have unicel  credentials to send sms my concern is in  which file i need to set up configuration for the above inorder to send sms.

**Comment by SimplyCorey** [comment]
Hey there,

Did you run `php artisan vendor:publish`? If so, the settings should be saved under `config/sms.php`

Let me know if you need anymore help!

**Comment by parithiban** [comment]
Hi,

Thanks for the reply.I got the sms configuration after installing "smart-crowd/simple-sms-drivers".
My Question is this:

if  i hit this url through **curl** i am able to send sms how to implement this in your package??
`http://api.unicel.in/SendSMS/sendmsg.php?uname=XXXXX&pass=XXXXX&send=XXXX&dest=91".$mobilenumber."&msg=".$bodycontent."&concat=1`

And where to set the sms driver credentials for unicel in your package list as there are only some defined drivers are given

**Comment by SimplyCorey** [comment]
I am confused.  I am unable to find `smart-crowd/simple-sms-drivers`

We do not currently have a driver for Unicel.  If you wanted to create one, you would need to create a new driver using the `DriverInterface` class.  Afterwards you would need to register this with the `DriverManager` and set your `config/sms.php` config file.  

I would suggest looking at one of the current drivers for more information.  `CallFire` would be a great example and you would not need to adjust much of the class.

https://github.com/SimpleSoftwareIO/simple-sms/blob/master/src/SimpleSoftwareIO/SMS/Drivers/CallFireSMS.php

I may be able to add this driver to our official package.  Does Unicel have a free tier that I can use to build this class?

**Comment by Ellrion** [comment]
@SimplyCorey , @parithiban talks about (https://github.com/SmartCrowd/simple-sms-drivers)
But I do not understand his problem

**Comment by SimplyCorey** [comment]
I'm not sure of the exact issue as well.  @parithiban  Please clarify.
