### ISSUE TITLE
Return the outgoing message in SMS send method

### ISSUE THREAD

**Issue by marfurt** [SimpleSoftwareIO/simple-sms#22]
Currently, the `send` method in SMS doesn't return anything. Returning the outgoing message created inside the method could be useful (for example for testing). Note that this is done by the equivalent `send` method of the Laravel Mailer class.

**Comment by SimplyCorey** [comment]
Hey,

I agree with you that this could be useful.  Feel free to make a pull request!

**Comment by marfurt** [comment]
There is a [new pull request](https://github.com/SimpleSoftwareIO/simple-sms/pull/23). Thank you
