### ISSUE TITLE
what does the $data represent in sending sms and how to send free sms

### ISSUE THREAD

**Issue by thomas-tewelde** [SimpleSoftwareIO/simple-sms#24]
Hi. For test i am trying to send verification code sms using the free email to sms gateway. What should i include in the $data variable ... and please share a way to send free sms. thankyou for ur help.
SMS::send('simple-sms::welcome', $data, function($sms) {
            $sms->to('+25416737319');
        });

**Comment by SimplyCorey** [comment]
The $data variable is the information past to the blade template.  It should be an array that will fill out any variables with the template.

If you are not using a template and instead using the simple method of passing a string as the first argument, $data should be null because it will not be used.

Does that help?

**Comment by SimplyCorey** [comment]
You may send a free sms using the Email driver.

```
//Email Driver Example
SMS::send('simple-sms::welcome', $data, function($sms) {
    $sms->to('+15555555555', 'att');
});
```

**Comment by thomas-tewelde** [comment]
Hi thankyou for ur reply. i was able to try that, however i am getting this error:

> InvalidArgumentException in FileViewFinder.php line 112:
> 
> No hint path defined for [simple-sms]
> 
> in FileViewFinder.php line 112
> 
> at FileViewFinder->getNamespaceSegments('simple-sms::welcome') in FileViewFinder.php line 90
> at FileViewFinder->findNamedPathView('simple-sms::welcome') in FileViewFinder.php line 76
> at FileViewFinder->find('simple-sms::welcome') in Factory.php line 151

**Comment by SimplyCorey** [comment]
You are calling a view that doesn't exists.  You need to replace `simple-sms::welcome` with a view within your `resources/views` folder.
