### ISSUE TITLE
Ability to add "type" parameter to Nexmo API Request

### ISSUE THREAD

**Issue by Nekudapsik** [SimpleSoftwareIO/simple-sms#25]
Hi,
I am using a Nexmo driver for sending SMS in Hebrew language. There is a problem with encoding, and to fix it I need to add a &type=unicode to HTTP requests and URL. Is there any conventional way of doing it?

**Comment by SimplyCorey** [comment]
There is not a way to do this currently.  I'll look into adding this in the future.

**Comment by SimplyCorey** [comment]
Fixed in `V3.0.0`
