### ISSUE TITLE
Was trying to use it with laravel 5.1.2

### ISSUE THREAD

**Issue by ghost** [SimpleSoftwareIO/simple-sms#3]
Hello,
Was trying to use it with my application which is on laravel 5.1.2. To my composer.json i added this line "simplesoftwareio/simple-sms": "dev-master" in requirement section. It gave following error (Please check screen shot). Any suggestion. Thanks
![screen shot 2015-06-25 at 11 43 05 am](https://cloud.githubusercontent.com/assets/3293359/8351700/9be9dbf4-1b2f-11e5-9b99-b1be5a77b59f.png)

**Comment by SimplyCorey** [comment]
I haven't tried this with Laravel 5.1 yet.  I'll take a look shortly and see what is going on.

**Comment by SimplyCorey** [comment]
Fixed in latest dev branch.

**Comment by ghost** [comment]
Thanks @SimplyCorey
