### ISSUE TITLE
Error on sending multiple messages

### ISSUE THREAD

**Issue by marfurt** [SimpleSoftwareIO/simple-sms#30]
Sending multiple messages with drivers that use the Guzzle client (like Nexmo) returns an error on the second and subsequent messages.

```
try {
    SMS::send('Hello #1', [], function($sms) {
        $sms->to('xxx');
    });

    SMS::send('Hello #2', [], function($sms) {
        $sms->to('xxx');
    });
}
catch (\GuzzleHttp\Exception\ClientException $e) {
    var_dump($e->getResponse()->getBody()->getContents());
}
```

If you run this code, the first message will be correctly sent but you will get a "405 Not Allowed" response for the second message. The reason is that the `AbstractSMS` class doesn't build a new query for each request, but appends the query to the base URL (see the `buildCall` method). As a consequence, the URL is wrong on the second call, since we obtain `https://rest.nexmo.com/sms/json/sms/json` instead of `https://rest.nexmo.com/sms/json`. 

It's not a problem to use a shared SMS instance with a single client, however each call should be independent. In my opinion, the message body, query and parameters should not be bound to the client instance.

**Comment by SimplyCorey** [comment]
Thanks for the report.  The current package has some design flaws that I would to address soon.  I agree that a request object needs to be created that the should be separated from the each sms client.

**Comment by marfurt** [comment]
Since we need this feature in a current project, I've [forked](https://github.com/Apiness/simple-sms) yours and made changes so we can use it.

I haven't proposed a pull request because I've made a lot of modifications and only tested with Nexmo, but tell me if you're interested in it.

**Comment by SimplyCorey** [comment]
@marfurt I took a look at the fork and I will be taking some of these modifications.  Thank you for your work!

**Comment by SimplyCorey** [comment]
Fixed in latest dev branch.  Shipping today.
