### ISSUE TITLE
Installation problem in laravel 5.2

### ISSUE THREAD

**Issue by stojankukrika** [SimpleSoftwareIO/simple-sms#35]
Hi,
I try to install it on my laravel application whic use last laravel 5.2 but have a problem. Composer return me an error:
`  Problem 1

```
- Conclusion: remove laravel/framework v5.2.37
- Conclusion: don't install laravel/framework v5.2.37
- Conclusion: don't install laravel/framework v5.2.36
- Conclusion: don't install laravel/framework v5.2.35
- Conclusion: don't install laravel/framework v5.2.34
- Conclusion: don't install laravel/framework v5.2.33
- Conclusion: don't install laravel/framework v5.2.32
- Conclusion: don't install laravel/framework v5.2.31
- Conclusion: don't install laravel/framework v5.2.30
- Conclusion: don't install laravel/framework v5.2.29
- Conclusion: don't install laravel/framework v5.2.28
- Conclusion: don't install laravel/framework v5.2.27
- Conclusion: don't install laravel/framework v5.2.26
- Conclusion: don't install laravel/framework v5.2.25
- Conclusion: don't install illuminate/http v5.2.37
- Conclusion: don't install laravel/framework v5.2.24
- Conclusion: don't install illuminate/http v5.2.32
- Conclusion: don't install laravel/framework v5.2.23
- Conclusion: don't install illuminate/http v5.2.31
- Conclusion: don't install laravel/framework v5.2.22
- Conclusion: don't install illuminate/http v5.2.28
- Conclusion: don't install laravel/framework v5.2.21
- Conclusion: don't install illuminate/http v5.2.27
- Conclusion: don't install laravel/framework v5.2.20
- Conclusion: don't install illuminate/http v5.2.26
- Conclusion: don't install laravel/framework v5.2.19
- Conclusion: don't install illuminate/http v5.2.25
- Conclusion: don't install laravel/framework v5.2.18
- Conclusion: don't install illuminate/http v5.2.24
- Conclusion: don't install laravel/framework v5.2.17
- Conclusion: don't install illuminate/http v5.2.21
- Conclusion: don't install laravel/framework v5.2.16
- Conclusion: don't install illuminate/http v5.2.19
- Conclusion: don't install laravel/framework v5.2.15
- Conclusion: don't install laravel/framework v5.2.14
- Conclusion: don't install laravel/framework v5.2.13
- Conclusion: don't install illuminate/http v5.2.0
- Conclusion: don't install laravel/framework v5.2.12
- Conclusion: remove laravelcollective/html v5.2.4
- Conclusion: don't install illuminate/support v5.1.31
- Conclusion: don't install laravel/framework v5.2.11
- Conclusion: don't install illuminate/http v5.2.7
- Conclusion: don't install laravel/framework v5.2.10
- Conclusion: don't install illuminate/http v5.2.6
- Conclusion: don't install laravel/framework v5.2.9
- Conclusion: don't install laravelcollective/html v5.2.4
- Conclusion: don't install laravel/framework v5.2.8
- Conclusion: don't install laravelcollective/html v5.2.3
- Conclusion: don't install laravel/framework v5.2.7
- Conclusion: don't install laravelcollective/html v5.2.2
- Conclusion: don't install laravel/framework v5.2.6
- Conclusion: don't install laravelcollective/html v5.2.1
- Conclusion: don't install laravel/framework v5.2.5
- Conclusion: don't install illuminate/support v5.1.30
- Conclusion: don't install laravel/framework v5.2.4
- Conclusion: don't install laravel/framework v5.2.3
- Conclusion: don't install laravel/framework v5.2.2
- Installation request for spatie/laravel-backup ~3.5 -> satisfiable by spatie/laravel-backup[3.5.0, 3.6.0, 3.6.1,
- Installation request for laravelcollective/html 5.2.* -> satisfiable by laravelcollective/html[v5.2, v5.2.1, v5.2
- Conclusion: don't install illuminate/support v5.1.28
- Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.10, v5.
```

19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30,
2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9].
    - cartalyst/stripe-laravel v2.0.4 requires illuminate/support 5.0._|5.1._ -> satisfiable by illuminate/support[v5.0
v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - cartalyst/stripe-laravel v2.0.5 requires illuminate/support 5.0._|5.1._ -> satisfiable by illuminate/support[v5.0
v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.0
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.22
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.25
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.26
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.28
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.33
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.0.4
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.1
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.13
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.16
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.2
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.20
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.22
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.25
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.6
    - don't install laravel/framework v5.2.0|don't install illuminate/support v5.1.8
    - laravelcollective/html v5.2 requires illuminate/http 5.2.\* -> satisfiable by laravel/framework[v5.2.37, v5.2.0, v
.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29
5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9], illuminate/http[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5
    - Conclusion: don't install laravel/framework v5.2.1|install illuminate/support v5.1.28|install illuminate/support
    - Conclusion: don't install guzzlehttp/guzzle 6.2.0|install cartalyst/stripe-laravel v2.0.4|install cartalyst/strip
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1|install cartalyst/stripe-laravel v2.0.4|install cartalyst/strip
    - Conclusion: don't install guzzlehttp/guzzle 6.1.0|install cartalyst/stripe-laravel v2.0.4|install cartalyst/strip
    - Conclusion: don't install guzzlehttp/guzzle 6.0.2|install cartalyst/stripe-laravel v2.0.4|install cartalyst/strip
    - Conclusion: don't install guzzlehttp/guzzle 6.0.1|install cartalyst/stripe-laravel v2.0.4|install cartalyst/strip
    - Conclusion: remove guzzlehttp/guzzle 5.3.0|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2|instal
tp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.1|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.2|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.3|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.4|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.5|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.6|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.7|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.8|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.9|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2
uzzlehttp/guzzle 6.2.0
    - Conclusion: remove cartalyst/stripe v1.0.9|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.2|instal
tp/guzzle 6.2.0
    - Conclusion: remove cartalyst/stripe-laravel v2.0.3|install guzzlehttp/guzzle 6.0.1|install guzzlehttp/guzzle 6.0.
guzzlehttp/guzzle 6.2.0
    - simplesoftwareio/simple-sms 2.0.0 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1,
    - simplesoftwareio/simple-sms 2.1.0 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1,
    - simplesoftwareio/simple-sms 2.1.1 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1,
    - Conclusion: don't install simplesoftwareio/simple-sms 2.1.2|don't install cartalyst/stripe v1.0.0|keep guzzlehttp
0.2|install guzzlehttp/guzzle 6.1.0|install guzzlehttp/guzzle 6.1.1|install guzzlehttp/guzzle 6.2.0
    - Conclusion: don't install cartalyst/stripe v1.0.0|don't install guzzlehttp/guzzle 6.0.0|keep guzzlehttp/guzzle 5.
    - cartalyst/stripe-laravel v2.0.3 requires cartalyst/stripe 1.0.\* -> satisfiable by cartalyst/stripe[v1.0.9, v1.0.0
    - Installation request for cartalyst/stripe-laravel ~2.0.3 -> satisfiable by cartalyst/stripe-laravel[v2.0.3, v2.0.
    - Installation request for simplesoftwareio/simple-sms ~2 -> satisfiable by simplesoftwareio/simple-sms[2.0.0, 2.1.
`

**Comment by SimplyCorey** [comment]
@stojankukrika Please post your composer.json file.

**Comment by stojankukrika** [comment]
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2._",
    "netshell/paypal": "dev-master",
    "laravelcollective/html": "5.2._",
    "laracasts/flash": "~2.0",
    "yajra/laravel-datatables-oracle": "~6.10.1",
    "mews/captcha": "~2.1",
    "cartalyst/sentinel": "2.0._",
    "barryvdh/laravel-dompdf": "0.6._",
    "tymon/jwt-auth": "1.0.0-alpha.2",
    "dingo/api": "1.0.0-beta3",
    "maddhatter/laravel-fullcalendar": "~1.2.4",
    "laravel/cashier": "~5.0.15",
    "intervention/image": "~2.3.7",
    "pusher/pusher-php-server": "~2.3",
    "spatie/laravel-backup": "~3.5",
    "league/flysystem-dropbox": "~1.0.4",
    "venturecraft/revisionable": "1.27.",
    "efriandika/laravel-settings": "~1.2.3",
    "league/flysystem-aws-s3-v3": "~1.0.10",
    "aloha/twilio": "~2.0.0",
    "stripe/stripe-php": "~3.0",
    "omnipay/paypal": "~2.5.4",
    "omnipay/common": "~2.3.4",
    "ignited/laravel-omnipay": "~2.1.0",
    "paypal/adaptivepayments-sdk-php":"~3.9.2",
    "cartalyst/stripe-laravel": "~2.0.3",
    "simplesoftwareio/simple-sms": "~2"
  },
  "require-dev": {
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9._",
    "phpunit/phpunit": "~4.0",
    "symfony/css-selector": "2.8._|3.0._",
    "symfony/dom-crawler": "2.8._|3.0.*"
  },
  "autoload": {
    "classmap": [
      "database"
    ],
    "psr-4": {
      "App\": "app/"
    }
  },
  "autoload-dev": {
    "classmap": [
      "tests/TestCase.php"
    ]
  },
  "scripts": {
    "post-root-package-install": [
      "php -r \"copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "php artisan key:generate"
    ],
    "post-install-cmd": [
      "Illuminate\Foundation\ComposerScripts::postInstall",
      "php artisan optimize"
    ],
    "post-update-cmd": [
      "Illuminate\Foundation\ComposerScripts::postUpdate",
      "php artisan optimize"
    ]
  },
  "config": {
    "preferred-install": "dist"
  }
}

**Comment by SimplyCorey** [comment]
`cartalyst/stripe-laravel` is conflicting with the package and needs to be upgrading to version ~4.  `cartalyst/stripe-laravel` ~2 is using an older guzzle package which conflicts with the guzzle package required by simple-sms.

Changing `"cartalyst/stripe-laravel": "~2.0.3",` to `"cartalyst/stripe-laravel": "~4",` will solve the conflict.

**Comment by stojankukrika** [comment]
Thank you very much! Great! It's works! You are the best! :+1:
