### ISSUE TITLE
outdated nexmo api endpoints

### ISSUE THREAD

**Issue by daryledesilva** [SimpleSoftwareIO/simple-sms#37]
Hello, i've tried using https://www.simplesoftware.io/docs/simple-sms

and i have the trial account for nexmo

I think the api endpoints you are using for nexmo are already outdated

example errors:

```
exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://rest.nexmo.com/search/messages/9378dc7e/440bd0ebef80e567` resulted in a `400 Bad Request` response:
```

```
exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://rest.nexmo.com/sms/json/search/messages/9378dc7e/440bd0ebef80e567?from=from&to=1212345678&text=test&api_key=xxxxxxxx&api_secret=xxxxxxxxxxxxxxxx` resulted in a `404 Not Found` response:
```

in my test i used the send sms method and also the fetch all messages. both returned 400 bad requests.

i have checked nexmo documentation and they're using different urls now
like this

```
https://rest.nexmo.com/sms/json?api_key=&api_secret=&to=&from=
```

**Comment by SimplyCorey** [comment]
@daryledesilva this was a known bug in how the calls were being built in 2.0 and should be fixed in 3.0.  Will you give it a try and see if there is any issues?  I have tried it on my side and everything is working.

**Comment by daryledesilva** [comment]
ok ill double check from my side again. cheers!

**Comment by SimplyCorey** [comment]
@daryledesilva Worked on 3.0?
