### ISSUE TITLE
Mention L5 dependencies in docs 

### ISSUE THREAD

**Issue by sdeering** [SimpleSoftwareIO/simple-sms#4]
Hi guys, I thought to mention L5 dependencies in the docs.

![image](https://cloud.githubusercontent.com/assets/1787454/8444426/b6b207ba-1fd3-11e5-91ec-d56828164c23.png)

What features of Guzzle 6.0.\* are you using?

**Comment by SimplyCorey** [comment]
I haven't thoroughly tested the dev branch yet.  We aren't using any new features and we may drop down to 5.\* due to this.  Thank you for pointing this out!

**Comment by sdeering** [comment]
Thanks mate

**Comment by SimplyCorey** [comment]
Added.
