### ISSUE TITLE
Can't get Log driver to work

### ISSUE THREAD

**Issue by DaveTheCrane** [SimpleSoftwareIO/simple-sms#40]
Hi,

I've installed your package in my Laravel 5.2.39 app, and successfully used it to send SMS via Twilio, so I know everything's set up correctly. Very impressed by the ease of use, and similarity to the mailer interface is a nice touch. So big thanks for your code, and releasing it as open source.

One thing's giving me problems though.

I'd like to switch to a mocked-out driver for dev environments, for cost and convenience. The Log driver described in the docs sounds ideal:

https://www.simplesoftware.io/docs/simple-sms#docs-log-driver

When I try to use that, though, I get an error:

```
InvalidArgumentException in Manager.php line 90: Driver [log] not supported.
in Manager.php line 90
at Manager->createDriver('log') in Manager.php line 63
at Manager->driver() in SMSServiceProvider.php line 68
at SMSServiceProvider->SimpleSoftwareIO\SMS\{closure}(object(Application)) in Container.php line 289
```

Looking through the DriverManager code, and in the source for your package, I note that the Drivers folder doesn't contain a LogSMS.php file or similar.

Is the Log driver still supported? If not, what do you recommend for mocking purposes? I'm wondering if I can use the email driver with a mocked-out/logging mail setup, maybe?

Thanks much,

Dave

**Comment by SimplyCorey** [comment]
Did you install V3?  This was a new feature with V3 and does not exist in V2.

**Comment by DaveTheCrane** [comment]
Hi Corey,

Nope, schoolboy error on my part! I had v2 installed (composer.json require:{} as follows):

```
"simplesoftwareio/simple-sms": "~2"
```

Updated to "3.0.*" (like it says on your doc page, dunno where I'd got the v2 from), and it works.

Thanks, Dave
