### ISSUE TITLE
SMSNotSentException, verify undifiened when using Plivo SMS

### ISSUE THREAD

**Issue by masum110011** [SimpleSoftwareIO/simple-sms#44]
when using plivo sms to send sms, throws "**SMSNotSentException**" not found so I soved it by defining my own "SMSNotSentException" method in "vendor/simplesoftwareio/simple-sms/src/Drivers/PlivoSMS.php".  
Also define a protected $verify ...property on inside the class, outside of any methods. Else wil throw errors,
You can get the success response by adding few lines in "send: method in the same file. Just add a else block when response!=202 i.e. success.

**Comment by SimplyCorey** [comment]
Can you send me a diff file or pull request so I can see the changes?

**Comment by SimplyCorey** [comment]
@masum110011 Any feedback?
