### ISSUE TITLE
Twilio Receive Messages Error

### ISSUE THREAD

**Issue by N02SRT** [SimpleSoftwareIO/simple-sms#48]
Hello,

I have been using Simple-SMS for sending messages with Twilio, and it works great. :)

I just recently started working with receiving messages, and I keep getting an error:
 
![image](https://cloud.githubusercontent.com/assets/14588565/19930256/f691689e-a0dd-11e6-902e-689788c0e177.png)

I am using Laravel 5.2, SimpleSMS 3.0.1, and Guzzle 6.0.

Any Idea what would be causing this?

Thanks!

**Comment by SimplyCorey** [comment]
@N02SRT Can I see the code you are using to receive please?  Thanks

**Comment by N02SRT** [comment]
Sure thing. Here it is:

> public function view()
>     {
>         $messages = SMS::checkMessages();
>         foreach ($messages as $message)
>         {
>             //Will display the message of each retrieve message.
>             echo $message;
>         }
>     }

**Comment by SimplyCorey** [comment]
Thanks, I am looking into this.

**Comment by SimplyThomas** [comment]
This package has been abandoned in favor of http://laravel-notification-channels.com/
