### ISSUE TITLE
Unable to send SMS with EZTexting

### ISSUE THREAD

**Issue by ericp1337** [SimpleSoftwareIO/simple-sms#5]
``` html
InvalidArgumentException in Client.php line 387:
Passing in the "body" request option as an array to send a POST request has been deprecated.
Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data reque
```

**Comment by SimplyCorey** [comment]
Is this for Laravel 4 or 5?

**Comment by ericp1337** [comment]
Laravel 5

On July 31, 2015 12:59:01 PM CDT, Corey McCormick notifications@github.com wrote:

> Is this for Laravel 4 or 5?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SimpleSoftwareIO/simple-sms/issues/5#issuecomment-126771765

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SimplyCorey** [comment]
I have a bunch of updates for this that I'll be pushing soon.

**Comment by SimplyCorey** [comment]
Fixed in latest dev-master.
