### ISSUE TITLE
Can´t send sms with Zenvia

### ISSUE THREAD

**Issue by diogolast** [SimpleSoftwareIO/simple-sms#50]
Hello,

I am trying to send SMS with Zenvia and I getting:

> FatalThrowableError in ZenviaSMS.php line 41:
> Call to undefined method SimpleSoftwareIO\SMS\Drivers\ZenviaSMS::setUser()

This is the function I am calling.
```
        SMS::send('teste', null, function ($sms) {
            $sms->to('+5599999999999');
        });
```

I am using Laravel 5.2, SimpleSMS 3.0.1, and Guzzle 6.0.

Any Idea what would be causing this?

Thanks!

**Comment by SimplyCorey** [comment]
I just checked the code for this and see that the `MakesRequests` trait is on this driver which has that function.  Do you have any other debugging information I can look at?  Did you set your API settings in config/sms.php?  What PHP version are you using?

**Comment by diogolast** [comment]
Yes, I have set the API settings. I am using Laravel Homestead with PHP 7. I searched for the MakesRequests on Zenvia driver and I haven't found. Can you check the master branch on 3.0.1?

Thanks

**Comment by SimplyCorey** [comment]
I see the issue.  The driver has it on develop but it never made it to the master branch.  Sorry about that! Ill push out a bug fix tomorrow.

**Comment by diogolast** [comment]
Thanks!!!

**Comment by fabiogalera** [comment]
Hello,

When the version 3.0.2 will come out ? Would like to have this fixed.

**Comment by SimplyCorey** [comment]
@filipegar I will get the release out this week.

**Comment by SimplyCorey** [comment]
Releasing the next version in a few minutes.
