### ISSUE TITLE
Api params should be in config

### ISSUE THREAD

**Issue by Rhincodon** [SimpleSoftwareIO/simple-sms#51]
Example: NexmoDriver has property `$apiEnding` that applies to every request. Its set to `type=unicode` now. People might not need unicode, its just not default param that some user requested in his issue and that issue has accepted. That param controlling max length of message, and sms is forced to be 70 chars for now.

**Comment by SimplyCorey** [comment]
@Rhincodon, I agree.  I am currently on vacation and wont be able to address this until I get back.  Feel free to make a pull request though to fix the issue.

**Comment by SimplyThomas** [comment]
This project has been abandoned. This enhancement will never come to light.
