### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by JuanS-zz** [SimpleSoftwareIO/simple-sms#52]
Hi there, I'm migrating a project from Laravel to Lumen and can't get your component working properly.

I get the following error 
```
FatalThrowableError in Manager.php line 77:
Too few arguments to function Illuminate\Support\Manager::createDriver(), , 0 passed in /var/www/vendor/illuminate/support/Manager.php on line 87 and exactly 1 expected
```

Any idea?

**Comment by SimplyCorey** [comment]
I will need to review the code.  I would like to get a Lumen part added to the docs.
