### ISSUE TITLE
Critical error -- Laravel 5.4 deprecated "share" method. Use singleton instead.

### ISSUE THREAD

**Issue by SaltedBlowfish** [SimpleSoftwareIO/simple-sms#54]
See line 50 of SMSServiceProvider.php in the package. As I stated in the title, Laravel deprecated the `share` method that's being used here. 

```
/**
 * Register the correct driver based on the config file.
 */
public function registerSender()
{
    $this->app['sms.sender'] = $this->app->share(function ($app) {
        return (new DriverManager($app))->driver();
    });
}
```

Until this is fixed, the package is incompatible with Laravel 5.4.

**Comment by taishjason** [comment]
```
$this->app->singleton( 'sms.sender' , function ($app) {
     return new DriverManager($app)->driver();
});
```
Perhaps this work?

**Comment by SimplyCorey** [comment]
I have not tested this in 5.4 yet.  I have been pretty busy at work, but I plan on getting this address with the other issues soon.

**Comment by nunesbeto** [comment]
+1

**Comment by SimplyCorey** [comment]
I did some work on this tonight.  I need to do some code review before I make this change.  I plan on getting the next version of this released this week which would include this fix.

**Comment by mifas** [comment]
Still, has the error, `SMSServiceProvider@registerSender ` need to switch to singleton method.

**Comment by SimplyCorey** [comment]
See my comment above.

**Comment by turtlechase** [comment]
Still happens. 21 days passed. When will you be able to update? Thanks

**Comment by vesper8** [comment]
put this in my composer.json and am getting the latest fix which works

```
"simplesoftwareio/simple-sms": "dev-develop"
```

**Comment by SimplyCorey** [comment]
Out in 3.1.1
