### ISSUE TITLE
Does this module really need Guzzle 6.0?

### ISSUE THREAD

**Issue by mlanser** [SimpleSoftwareIO/simple-sms#6]
It seems quite a few Laravel modules do not yet support Guzzle 6.0 (e.g. Laravel Socialite) and I get conflicts when I try to run "composer update". Does this module absolutely require Guzzle 6? Or am I missing something?

TIA,
-martin.

**Comment by SimplyCorey** [comment]
We made a code change (https://github.com/SimpleSoftwareIO/simple-sms/commit/919e115de17ecb3f0b8a42ce5358a95f18cf9a75) to upgrade to Guzzle 6.  You could fork the package and reverse the change to you Guzzle 5 and below.  

Are there any other popular Laravel modules that do not support Guzzle 6?  We may reverse this change if there are to many conflicts in the wild.

**Comment by mlanser** [comment]
@SimplyCorey thx for your reply ... I will try to check which other Laravel packages have issues with Guzzle 6. I thought I found at least 2, but there could be more. I will play with this a bit over next few days and will let you know. Worst case I just fork this temporarily (as per your suggestion).

**Comment by SimplyCorey** [comment]
Added to read me.
