### ISSUE TITLE
Class sms does not exist error

### ISSUE THREAD

**Issue by chadpriddle** [SimpleSoftwareIO/simple-sms#64]
I got the alias and and serviceproviders and then sms.php config file setup. I add "use SMS" in my controller and i get this error:
Class 'SMS' not found

I then change it to "use SimpleSoftwareIO\SMS\Facades\SMS;" then i get this error:
ReflectionException in Container.php line 734:
Class sms does not exist

Here is my function I'm trying to execute in the controller:
`SMS::send('Your SMS Message', null, function($sms) {
    $sms->to('+15555555555');
});`

Any thoughts?

**Comment by SimplyCorey** [comment]
It sounds like you havnt pulled in the correct file.  Add `use SimpleSoftwareIO\SMS\Facades\SMS;` to the top of the file and it should work.

**Comment by chadpriddle** [comment]
I've tried both:

use SimpleSoftwareIO\SMS\Facades\SMS;
use SMS;

Same error.

**Comment by SimplyCorey** [comment]
Let me see your app.php file.  It sounds like it has not been registered correctly.

**Comment by chadpriddle** [comment]
Service Providers:
SimpleSoftwareIO\SMS\SMSServiceProvider::class;

Alias:
'SMS' => SimpleSoftwareIO\SMS\Facades\SMS::class;
