### ISSUE TITLE
laravel 5.4

### ISSUE THREAD

**Issue by linares82** [SimpleSoftwareIO/simple-sms#65]
I use it in laravel 5.4 and obtain :
[Symfony\Component\Debug\Exception\FatalErrorException]
Call to undefined method Illuminate\Foundation\Application::share()

I found the problem in file SMSService provider line 51 
$this->app['sms.sender'] = $this->app->share(function ($app) {
            return (new DriverManager($app))->driver();
        });

but i dind't know the correct way to mede it works

**Comment by seandelaney** [comment]
I also have the same issue.

**Comment by seandelaney** [comment]
I have fixed it locally since the deprecated share() method has been removed.

I changed:

```
$this->app['sms.sender'] = $this->app->share(function($app) {
     return (new DriverManager($app))->driver();
});
```

to this:

```
$this->app->singleton('sms.sender', function ($app) {
	return (new DriverManager($app))->driver();
});
```

**Comment by SimplyCorey** [comment]
This has been fixed on 3.1.1.  You need to update.

**Comment by SimplyThomas** [comment]
@seandelaney is correct in the implementation to support Laravel 5.4 if you are not up-to-date with the latest version of Simple-SMS.

This was updated in 9d20dbd09cee1ace277cab4cbeb1bfbf023843d6 which is both on the master and dev branches, having been released in 93e7feb7a1f76634b49247bb5849f06a879a3fb4 3.1.1.

If you have any other problems, don't hesitate to open another issue.

**Comment by seandelaney** [comment]
I have now updated to 3.1.1.

Thanks

**Comment by samarhaider** [comment]
Its not supported on php 5.6.

I am getting following error

```
  Problem 1
    - Installation request for simplesoftwareio/simple-sms 3.1.1 -> satisfiable by simplesoftwareio/simple-sms[3.1.1].
    - simplesoftwareio/simple-sms 3.1.1 requires php >=7.0.0 -> your PHP version (5.6.23) does not satisfy that requirement.

```

**Comment by SimplyCorey** [comment]
@samarhaider PHP 7 is required.

**Comment by samarhaider** [comment]
But on site mention PHP: >= 5.5 
https://www.simplesoftware.io/docs/simple-sms#docs-requirements

**Comment by SimplyCorey** [comment]
Strange, ill fix that.

**Comment by samarhaider** [comment]
Can you available this for php>= 5.5?

**Comment by MelonSmasher** [comment]
Laravel 5.4 requires php >= 5.6.4. 

https://laravel.com/docs/5.4

**Comment by samarhaider** [comment]
But I am using PHP 5.6.23, simple-sms should be support this not only php 7

**Comment by SimplyThomas** [comment]
@samarhaider We use functions and features that were introduced in PHP 7.0.0 and it is currently our baseline PHP version to run Simple-SMS. I will be updating the docs to reflect this accurately.

If you are using Laravel 5.4 (since you are making your comments on a Laravel 5.4 issue that was closed), your current PHP version could also run into issues with your base Laravel installation down the road. I recommend you upgrade your version of PHP.
