### ISSUE TITLE
Fix readme doc

### ISSUE THREAD

**Issue by Ellrion** [SimpleSoftwareIO/simple-sms#7]
How about delete all information about install package on laravel version 4 from readme in version 2? Juste create link to 1.\* relise https://github.com/SimpleSoftwareIO/simple-sms/tree/1.1.0

**Comment by SimplyCorey** [comment]
We plan on moving the 4 to a new document completely.  Feel free to pull request!

**Comment by SimplyCorey** [comment]
Fixed in latest master.
