### ISSUE TITLE
Twilio outdated

### ISSUE THREAD

**Issue by seldimi** [SimpleSoftwareIO/simple-sms#71]
Hello. I have been trying to setup the simple SMS on Laravel where I use Twilio as standalone and I get this message. 
simplesoftwareio/simple-sms 3.0.1 requires twilio/sdk ~4

But Twilio is 5.8 now... Any easy ideas or fixes?

**Comment by SimplyCorey** [comment]
I would need to check the changes.  It will be awhile till I get around to it as I am busy with other projects at the moment.  Feel free to make the changes and create a pull request.

**Comment by alexmolosh** [comment]
it has been 2+ months with no action.
Mark package as abandoned. Noone uses old twilio.

**Comment by SimplyCorey** [comment]
@alexmolosh What exactly have you done to support this package?  Did you make a PR?

**Comment by SimplyCorey** [comment]
Coming in here with your shit attitude will get you nothing.

**Comment by SimplyCorey** [comment]
Or open an bounty and pay for this project to be supported.  Unless you have something positive to contribute, see your way out.

**Comment by alexmolosh** [comment]
Support this package? Are you joking?
I am supporting useful modules, not those that are not even available for install.
You are wasting time of good people - they are trying to use it in vain.
You should be honest to everybody. "Needs funding to make it work" is a status for your package.

**Comment by SimplyCorey** [comment]
@alexmolosh You have 1 commit over a year on GitHub.  You are not supporting any useful open source projects.  I believe I saved you time.  You can fork the project and fix it and PR it.  Or you can waste even more time and rewrite it from scratch.  I'm not joking, and your showing your ass.  Again, make a PR or go kick rocks.

**Comment by SimplyThomas** [comment]
Let's do our best to remain civil and constructive with our comments. There's no reason to be blatantly disrespectful towards anyone -- if you have an issue with an open sourced package, you are more than welcome to do your part to contribute by providing constructive issues, conversation, or even taking the time required to add code.

This package has been abandoned in favor of http://laravel-notification-channels.com/
