### ISSUE TITLE
Dynamic driver

### ISSUE THREAD

**Issue by kjdion84** [SimpleSoftwareIO/simple-sms#74]
I looked at the code and can see you are using `$this->app` in order to acquire driver values.

My question is - does this support dynamic driver values? Let's say that I am creating an application and want the person to be able to choose a driver and then enter their keys in a form, which would be saved in the database. 

Does this package support that? Wouldn't it be better to allow someone to use their own array of values rather than relying on config files?

**Comment by SimplyThomas** [comment]
Being able to dynamically assign drivers is currently outside of the scope of this project. It's not impossible to do using simple-sms as a framework, but it is not something that we are going to add and later support.

**Comment by SimplyCorey** [comment]
You could easily extend our service provider and make your own and then add this one to your config/app.php file.
