### ISSUE TITLE
Having issue

### ISSUE THREAD

**Issue by milindrc** [SimpleSoftwareIO/simple-sms#77]
Call to undefined method Illuminate\Foundation\Application::share()
I encountered this error whenever I send a message

**Comment by milindrc** [comment]
SMS::send('Your SMS Message', null, function($sms) {
        $sms->to('+919999333545');
    });

**Comment by SimplyCorey** [comment]
What version of Laravel?

**Comment by rxluz** [comment]
I've same error, then I changed my composer.json to "simplesoftwareio/simple-sms": "3.1.*" and now is OK.

The SimpleSoftwareIO docs needs be changed (in docs is written "simplesoftwareio/simple-sms": "3.0.*")

**Comment by chadpriddle** [comment]
Same issues updating to 3.1.* fixed it. I'm running laravel 5.5
